/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/6.7/samples
 */

plugins {
  java
  id("com.google.cloud.tools.jib") version "2.6.0"
}

jib {
  to {
    image = "ghcr.io/anuraaga/foobar"
  }
  from {
    image = "ghcr.io/github/super-linter:v3"
  }
  container {
    mainClass = "Application"
  }
}
